//>>built
(function(k,t){var n,l,e,q,E,p=function(){},r=function(a){for(var b in a)return 0;return 1},F={}.toString,v=function(a){return"[object Function]"==F.call(a)},w=function(a){return"[object String]"==F.call(a)},C=function(a){return"[object Array]"==F.call(a)},s=function(a,b){if(a)for(var c=0;a[c];)b(a[c++])},g=function(a,b){for(var c in b)a[c]=b[c];return a},z=function(a,b){return g(Error(a),{src:"dojoLoader",info:b})},G=1,pa=function(){return"_"+G++},f=function(a,b,c){return qa(a,b,c,0,f)},L=this,D=
L.document,Ga=D&&D.createElement("DiV"),x=f.has=function(a){return v(H[a])?H[a]=H[a](L,D,Ga):H[a]},H=x.cache=t.hasCache;x.add=function(a,b,c,d){(void 0===H[a]||d)&&(H[a]=b);return c&&x(a)};for(var A in k.has)x.add(A,k.has[A],0,1);f.async=1;var Ha=new Function("return eval(arguments[0]);");f.eval=function(a,b){return Ha(a+"\r\n////@ sourceURL\x3d"+b)};var $={},J=f.signal=function(a,b){var c=$[a];s(c&&c.slice(0),function(a){a.apply(null,C(b)?b:[b])})},Ia=f.on=function(a,b){var c=$[a]||($[a]=[]);c.push(b);
return{remove:function(){for(var a=0;a<c.length;a++)if(c[a]===b){c.splice(a,1);break}}}},ra=[],Ja={},sa=[],aa={},ta=f.map={},O=[],u={},ba="",K={},P={};A={};var Q=0,S=function(a){var b,c,d,h;for(b in P)c=P[b],(d=b.match(/^url\:(.+)/))?K["url:"+ua(d[1],a)]=c:"*now"==b?h=c:"*noref"!=b&&(d=R(b,a),K[d.mid]=K["url:"+d.url]=c);h&&h(ca(a));P={}},va=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},da=function(a,b){b.splice(0,b.length);for(var c in a)b.push([c,a[c],RegExp("^"+
va(c)+"(/|$)"),c.length]);b.sort(function(a,b){return b[3]-a[3]});return b},Ka=function(a,b){s(a,function(a){b.push([w(a[0])?RegExp("^"+va(a[0])+"$"):a[0],a[1]])})},wa=function(a){var b=a.name;b||(b=a,a={name:b});a=g({main:"main"},a);a.location=a.location?a.location:b;a.packageMap&&(ta[b]=a.packageMap);a.main.indexOf("./")||(a.main=a.main.substring(2));aa[b]=a},xa=[],M=function(a,b,c){for(var d in a){"waitSeconds"==d&&(f.waitms=1E3*(a[d]||0));"cacheBust"==d&&(ba=a[d]?w(a[d])?a[d]:(new Date).getTime()+
"":"");if("baseUrl"==d||"combo"==d)f[d]=a[d];a[d]!==H&&(f.rawConfig[d]=a[d],"has"!=d&&x.add("config-"+d,a[d],0,b))}f.baseUrl||(f.baseUrl="./");/\/$/.test(f.baseUrl)||(f.baseUrl+="/");for(d in a.has)x.add(d,a.has[d],0,b);s(a.packages,wa);for(E in a.packagePaths)s(a.packagePaths[E],function(a){var b=E+"/"+a;w(a)&&(a={name:a});a.location=b;wa(a)});da(g(ta,a.map),O);s(O,function(a){a[1]=da(a[1],[]);"*"==a[0]&&(O.star=a)});da(g(Ja,a.paths),sa);Ka(a.aliases,ra);if(b)xa.push({config:a.config});else for(d in a.config)b=
I(d,c),b.config=g(b.config||{},a.config[d]);a.cache&&(S(),P=a.cache,a.cache["*noref"]&&S());J("config",[a,f.rawConfig])};f.rawConfig={};M(t,1);M(k,1);M(A,1);var T=function(a){ea(function(){s(a.deps,ya)})},qa=function(a,b,c,d,h){var m;if(w(a)){if((m=I(a,d,!0))&&m.executed)return m.result;throw z("undefinedModule",a);}C(a)||(M(a,0,d),a=b,b=c);if(C(a))if(a.length){c="require*"+pa();for(var e,G=[],k=0;k<a.length;)e=a[k++],G.push(I(e,d));m=g(U("",c,0,""),{injected:2,deps:G,def:b||p,require:d?d.require:
f,gc:1});u[m.mid]=m;T(m);var n=N&&0!="sync";ea(function(){fa(m,n)});m.executed||B.push(m);V()}else b&&b();return h},ca=function(a){if(!a)return f;var b=a.require;b||(b=function(c,d,h){return qa(c,d,h,a,b)},a.require=g(b,f),b.module=a,b.toUrl=function(b){return ua(b,a)},b.toAbsMid=function(b){return ga(b,a)});return b},B=[],W=[],y={},Ma=function(a){a.injected=1;y[a.mid]=1;a.url&&(y[a.url]=a.pack||1);La()},X=function(a){a.injected=2;delete y[a.mid];a.url&&delete y[a.url];r(y)&&Na()},Oa=f.idle=function(){return!W.length&&
r(y)&&!B.length&&!N},ha=function(a,b){if(b)for(var c=0;c<b.length;c++)if(b[c][2].test(a))return b[c];return 0},za=function(a){var b=[],c,d;for(a=a.replace(/\\/g,"/").split("/");a.length;)c=a.shift(),".."==c&&b.length&&".."!=d?(b.pop(),d=b[b.length-1]):"."!=c&&b.push(d=c);return b.join("/")},U=function(a,b,c,d){return{pid:a,mid:b,pack:c,url:d,executed:0,def:0}},Aa=function(a,b,c,d,h,m,f,e,G){var k,l,g,q;q=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||q&&!b)return U(0,a,0,a);a=za(q?b.mid+"/../"+a:
a);if(/^\./.test(a))throw z("irrationalPath",a);b&&(g=ha(b.mid,m));(g=(g=g||m.star)&&ha(a,g[1]))&&(a=g[1]+a.substring(g[3]));b=(n=a.match(/^([^\/]+)(\/(.+))?$/))?n[1]:"";(k=c[b])?a=b+"/"+(l=n[3]||k.main):b="";var p=0;s(e,function(b){var c=a.match(b[0]);c&&0<c.length&&(p=v(b[1])?a.replace(b[0],b[1]):b[1])});if(p)return Aa(p,0,c,d,h,m,f,e,G);if(c=d[a])return G?U(c.pid,c.mid,c.pack,c.url):d[a];d=(g=ha(a,f))?g[1]+a.substring(g[3]):b?k.location+"/"+l:a;/(^\/)|(\:)/.test(d)||(d=h+d);return U(b,a,k,za(d+
".js"))},R=function(a,b){return Aa(a,b,aa,u,f.baseUrl,O,sa,ra)},Ba=function(a,b,c){return a.normalize?a.normalize(b,function(a){return ga(a,c)}):ga(b,c)},Ca=0,I=function(a,b,c){var d,h;(d=a.match(/^(.+?)\!(.*)$/))?(h=I(d[1],b,c),5===h.executed&&!h.load&&ia(h),h.load?(d=Ba(h,d[2],b),a=h.mid+"!"+(h.dynamic?++Ca+"!":"")+d):(d=d[2],a=h.mid+"!"+ ++Ca+"!waitingForPlugin"),a={plugin:h,mid:a,req:ca(b),prid:d}):a=R(a,b);return u[a.mid]||!c&&(u[a.mid]=a)},ga=f.toAbsMid=function(a,b){return R(a,b).mid},ua=f.toUrl=
function(a,b){var c=R(a+"/x",b),d=c.url;return Da(0===c.pid?a:d.substring(0,d.length-5))},Ea={injected:2,executed:5,def:3,result:3};e=function(a){return u[a]=g({mid:a},Ea)};var Pa=e("require"),Qa=e("exports"),Ra=e("module"),Y={},ja=0,ia=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;return a},Sa=function(a){var b={};s(a.loadQ,function(c){var d=Ba(a,c.prid,c.req.module),f=a.dynamic?c.mid.replace(/waitingForPlugin$/,d):a.mid+"!"+d,d=g(g({},c),{mid:f,prid:d,injected:0});
u[f]||Fa(u[f]=d);b[c.mid]=u[f];X(c);delete u[c.mid]});a.loadQ=0;var c=function(a){for(var c=a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},d;for(d in u)c(u[d]);s(B,c)},ka=function(a){f.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=ja++;a.loadQ&&(ia(a),Sa(a));for(q=0;q<B.length;)B[q]===a?B.splice(q,1):q++;/^require\*/.test(a.mid)&&delete u[a.mid]},Ta=[],fa=function(a,b){if(4===a.executed)return f.trace("loader-circular-dependency",[Ta.concat(a.mid).join("-\x3e")]),!a.def||b?
Y:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return Y;var c=a.mid,d=a.deps||[],h,m=[],e=0;for(a.executed=4;h=d[e++];){h=h===Pa?ca(a):h===Qa?a.cjs.exports:h===Ra?a.cjs:fa(h,b);if(h===Y)return a.executed=0,f.trace("loader-exec-module",["abort",c]),Y;m.push(h)}f.trace("loader-run-factory",[a.mid]);c=a.def;m=v(c)?c.apply(null,m):c;a.result=void 0===m&&a.cjs?a.cjs.exports:m;ka(a)}return a.result},N=0,ea=function(a){try{N++,a()}finally{N--}Oa()&&J("idle",[])},V=function(){N||ea(function(){for(var a,
b,c=0;c<B.length;)a=ja,b=B[c],fa(b),a!=ja?c=0:c++})},Da=function(a){a+="";return a+(ba?(/\?/.test(a)?"\x26":"?")+ba:"")},Fa=function(a){var b=a.plugin;5===b.executed&&!b.load&&ia(b);var c=function(b){a.result=b;X(a);ka(a);V()};b.load?b.load(a.prid,a.req,c):b.loadQ?b.loadQ.push(a):(b.loadQ=[a],B.unshift(b),ya(b))},Z=0,la=0,ma=0,Ua=function(a,b){x("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));ma=1;a===Z?Z.call(null):f.eval(a,b.url);ma=0},ya=function(a){var b=a.mid,c=a.url;if(!a.executed&&
!a.injected&&!(y[b]||a.url&&(a.pack&&y[a.url]===a.pack||1==y[a.url])))if(Ma(a),a.plugin)Fa(a);else{var d=function(){Va(a);if(2!==a.injected){if(x("dojo-enforceDefine")){J("error",z("noDefine",a));return}X(a);g(a,Ea);f.trace("loader-define-nonmodule",[a.url])}V()};(Z=K[b]||K["url:"+a.url])?(f.trace("loader-inject",["cache",a.mid,c]),Ua(Z,a),d()):(f.trace("loader-inject",["script",a.mid,c]),la=a,f.injectUrl(Da(c),d,a),la=0)}},na=function(a,b,c){f.trace("loader-define-module",[a.mid,b]);if(2===a.injected)return J("error",
z("multipleDefine",a)),a;g(a,{deps:b,def:c,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var d=0;b[d];d++)b[d]=I(b[d],a);X(a);!v(c)&&!b.length&&(a.result=c,ka(a));return a},Va=function(a,b){for(var c=[],d,f;W.length;)f=W.shift(),b&&(f[0]=b.shift()),d=f[0]&&I(f[0])||a,c.push([d,f[1],f[2]]);S(a);s(c,function(a){T(na.apply(null,a))})},Na=p,La=p;x.add("ie-event-behavior",D.attachEvent&&"undefined"===typeof Windows&&("undefined"===
typeof opera||"[object Opera]"!=opera.toString()));var oa=function(a,b,c,d){if(x("ie-event-behavior"))return a.attachEvent(c,d),function(){a.detachEvent(c,d)};a.addEventListener(b,d,!1);return function(){a.removeEventListener(b,d,!1)}},Wa=oa(window,"load","onload",function(){f.pageLoaded=1;"complete"!=D.readyState&&(D.readyState="complete");Wa()});e=D.getElementsByTagName("script");for(q=0;!Q;)if(!/^dojo/.test((l=e[q++])&&l.type))Q=l;f.injectUrl=function(a,b,c){c=c.node=D.createElement("script");
var d=oa(c,"load","onreadystatechange",function(a){a=a||window.event;var c=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(c.readyState))d(),f(),b&&b()}),f=oa(c,"error","onerror",function(b){d();f();J("error",z("scriptError",[a,b]))});c.type="text/javascript";c.charset="utf-8";c.src=a;Q.parentNode.insertBefore(c,Q);return c};f.log=p;f.trace=p;l=function(a,b,c){var d=arguments.length,h=["require","exports","module"],e=[0,a,b];1==d?e=[0,v(a)?h:[],a]:2==d&&w(a)?e=[a,v(b)?h:[],b]:3==
d&&(e=[a,b,c]);f.trace("loader-define",e.slice(0,2));if((d=e[0]&&I(e[0]))&&!y[d.mid])T(na(d,e[1],e[2]));else if(!x("ie-event-behavior")||ma)W.push(e);else{d=d||la;if(!d)for(a in y)if((h=u[a])&&h.node&&"interactive"===h.node.readyState){d=h;break}d?(S(d),T(na(d,e[1],e[2]))):J("error",z("ieDefineFailed",e[0]));V()}};l.amd={vendor:"dojotoolkit.org"};g(g(f,t.loaderPatch),k.loaderPatch);Ia("error",function(a){try{if(console.error(a),a instanceof Error)for(var b in a);}catch(c){}});g(f,{uid:pa,cache:K,
packs:aa});L.define||(L.define=l,L.require=f,s(xa,function(a){M(a)}),l=A.deps||k.deps||t.deps,A=A.callback||k.callback||t.callback,f.boot=l||A?[l||[],A]:0)})(this.dojoConfig||this.djConfig||this.require||{},{async:1,hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:".",name:"dojo"},{location:"../dijit",name:"dijit"},{location:"../kitsonkelly-client",name:"kitsonkelly-client"}]});
require({cache:{"kitsonkelly-client/main":function(){define(["dojo/domReady!"],function(){})},"dojo/domReady":function(){define(["./has"],function(k){function t(e){r.push(e);p&&n()}function n(){if(!F){for(F=!0;r.length;)try{r.shift()(e)}catch(g){}F=!1;t._onQEmpty()}}var l=this,e=document,q={loaded:1,complete:1},E="string"!=typeof e.readyState,p=!!q[e.readyState],r=[],F;t.load=function(e,g,f){t(f)};t._Q=r;t._onQEmpty=function(){};E&&(e.readyState="loading");if(!p){var v=[],w=function(g){g=g||l.event;
p||"readystatechange"==g.type&&!q[e.readyState]||(E&&(e.readyState="complete"),p=1,n())},C=function(e,g){e.addEventListener(g,w,!1);r.push(function(){e.removeEventListener(g,w,!1)})};if(!k("dom-addeventlistener")){var C=function(e,g){g="on"+g;e.attachEvent(g,w);r.push(function(){e.detachEvent(g,w)})},s=e.createElement("div");try{s.doScroll&&null===l.frameElement&&v.push(function(){try{return s.doScroll("left"),1}catch(e){}})}catch(g){}}C(e,"DOMContentLoaded");C(l,"load");"onreadystatechange"in e?
C(e,"readystatechange"):E||v.push(function(){return q[e.readyState]});if(v.length){var z=function(){if(!p){for(var e=v.length;e--;)if(v[e]()){w("poller");return}setTimeout(z,30)}};z()}}return t})},"dojo/has":function(){define(["require","module"],function(k,t){var n=k.has||function(){};n.add("dom-addeventlistener",!!document.addEventListener);n.add("touch","ontouchstart"in document||0<window.navigator.msMaxTouchPoints);n.add("device-width",screen.availWidth||innerWidth);var l=document.createElement("form");
n.add("dom-attributes-explicit",0==l.attributes.length);n.add("dom-attributes-specified-flag",0<l.attributes.length&&40>l.attributes.length);n.clearElement=function(e){e.innerHTML="";return e};n.normalize=function(e,k){var l=e.match(/[\?:]|[^:\?]*/g),p=0,r=function(e){var k=l[p++];if(":"==k)return 0;if("?"==l[p++]){if(!e&&n(k))return r();r(!0);return r(e)}return k||0};return(e=r())&&k(e)};n.load=function(e,k,l){e?k([e],l):l()};return n})}}});
(function(){var k=this.require;k({cache:{}});!k.async&&k(["dojo"]);k.boot&&k.apply(null,k.boot)})();
//@ sourceMappingURL=dojo.js.map