//>>built
(function(h,m){var g,l=function(){},n=function(a){for(var b in a)return 0;return 1},y={}.toString,A=function(a){return"[object Function]"==y.call(a)},t=function(a){return"[object String]"==y.call(a)},r=function(a){return"[object Array]"==y.call(a)},s=function(a,b){if(a)for(var c=0;c<a.length;)b(a[c++])},f=function(a,b){for(var c in b)a[c]=b[c];return a},w=function(a,b){return f(Error(a),{src:"dojoLoader",info:b})},H=1,M=function(){return"_"+H++},e=function(a,b,c){return ra(a,b,c,0,e)},D=this,q=D.document,
Ha=q&&q.createElement("DiV"),u=e.has=function(a){return A(F[a])?F[a]=F[a](D,q,Ha):F[a]},F=u.cache=m.hasCache;u.add=function(a,b,c,d){(void 0===F[a]||d)&&(F[a]=b);return c&&u(a)};u.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);u("host-webworker")&&(f(m.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1}),m.loaderPatch={injectUrl:function(a,b){try{importScripts(a),b()}catch(c){}}});for(var B in h.has)u.add(B,
h.has[B],0,1);e.async=1;var Ia=new Function("return eval(arguments[0]);");e.eval=function(a,b){return Ia(a+"\r\n//# sourceURL\x3d"+b)};var ba={},I=e.signal=function(a,b){var c=ba[a];s(c&&c.slice(0),function(a){a.apply(null,r(b)?b:[b])})},Q=e.on=function(a,b){var c=ba[a]||(ba[a]=[]);c.push(b);return{remove:function(){for(var a=0;a<c.length;a++)if(c[a]===b){c.splice(a,1);break}}}},sa=[],Ja={},ta=[],ca={},ua=e.map={},R=[],v={},da="",J={},S={};B={};var K=0,U=function(a){var b,c,d,k;for(b in S)c=S[b],
(d=b.match(/^url\:(.+)/))?J["url:"+va(d[1],a)]=c:"*now"==b?k=c:"*noref"!=b&&(d=T(b,a,!0),J[d.mid]=J["url:"+d.url]=c);k&&k(ea(a));S={}},wa=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},fa=function(a,b){b.splice(0,b.length);for(var c in a)b.push([c,a[c],RegExp("^"+wa(c)+"(/|$)"),c.length]);b.sort(function(a,b){return b[3]-a[3]});return b},Ka=function(a,b){s(a,function(a){b.push([t(a[0])?RegExp("^"+wa(a[0])+"$"):a[0],a[1]])})},xa=function(a){var b=a.name;b||
(b=a,a={name:b});a=f({main:"main"},a);a.location=a.location?a.location:b;a.packageMap&&(ua[b]=a.packageMap);a.main.indexOf("./")||(a.main=a.main.substring(2));ca[b]=a},ya=[],N=function(a,b,c){for(var d in a){"waitSeconds"==d&&(e.waitms=1E3*(a[d]||0));"cacheBust"==d&&(da=a[d]?t(a[d])?a[d]:(new Date).getTime()+"":"");if("baseUrl"==d||"combo"==d)e[d]=a[d];a[d]!==F&&(e.rawConfig[d]=a[d],"has"!=d&&u.add("config-"+d,a[d],0,b))}e.baseUrl||(e.baseUrl="./");/\/$/.test(e.baseUrl)||(e.baseUrl+="/");for(d in a.has)u.add(d,
a.has[d],0,b);s(a.packages,xa);for(var k in a.packagePaths)s(a.packagePaths[k],function(a){var b=k+"/"+a;t(a)&&(a={name:a});a.location=b;xa(a)});fa(f(ua,a.map),R);s(R,function(a){a[1]=fa(a[1],[]);"*"==a[0]&&(R.star=a)});fa(f(Ja,a.paths),ta);Ka(a.aliases,sa);if(b)ya.push({config:a.config});else for(d in a.config)b=G(d,c),b.config=f(b.config||{},a.config[d]);a.cache&&(U(),S=a.cache,a.cache["*noref"]&&U());I("config",[a,e.rawConfig])},E=q.getElementsByTagName("script");g=0;for(var x,L,O;g<E.length;){x=
E[g++];if((L=x.getAttribute("src"))&&(O=L.match(/(((.*)\/)|^)dojo\.js(\W|$)/i)))L=O[3]||"",m.baseUrl=m.baseUrl||L,K=x;if(L=x.getAttribute("data-dojo-config")||x.getAttribute("djConfig"))B=e.eval("({ "+L+" })","data-dojo-config"),K=x}e.rawConfig={};N(m,1);N(h,1);N(B,1);var V=function(a){ga(function(){s(a.deps,za)})},ra=function(a,b,c,d,k){var p;if(t(a)){if((p=G(a,d,!0))&&p.executed)return p.result;throw w("undefinedModule",a);}r(a)||(N(a,0,d),a=b,b=c);if(r(a))if(a.length){c="require*"+M();for(var g,
h=[],q=0;q<a.length;)g=a[q++],h.push(G(g,d));p=f(W("",c,0,""),{injected:2,deps:h,def:b||l,require:d?d.require:e,gc:1});v[p.mid]=p;V(p);var n=P&&0!="sync";ga(function(){ha(p,n)});p.executed||C.push(p);X()}else b&&b();return k},ea=function(a){if(!a)return e;var b=a.require;b||(b=function(c,d,k){return ra(c,d,k,a,b)},a.require=f(b,e),b.module=a,b.toUrl=function(b){return va(b,a)},b.toAbsMid=function(b){return ia(b,a)});return b},C=[],Y=[],z={},Ma=function(a){a.injected=1;z[a.mid]=1;a.url&&(z[a.url]=
a.pack||1);La()},Z=function(a){a.injected=2;delete z[a.mid];a.url&&delete z[a.url];n(z)&&Na()},Oa=e.idle=function(){return!Y.length&&n(z)&&!C.length&&!P},ja=function(a,b){if(b)for(var c=0;c<b.length;c++)if(b[c][2].test(a))return b[c];return 0},Aa=function(a){var b=[],c,d;for(a=a.replace(/\\/g,"/").split("/");a.length;)c=a.shift(),".."==c&&b.length&&".."!=d?(b.pop(),d=b[b.length-1]):"."!=c&&b.push(d=c);return b.join("/")},W=function(a,b,c,d){return{pid:a,mid:b,pack:c,url:d,executed:0,def:0}},Ba=function(a,
b,c,d,k,p,e,g,h){var q,n,f,y;y=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||y&&!b)return W(0,a,0,a);a=Aa(y?b.mid+"/../"+a:a);if(/^\./.test(a))throw w("irrationalPath",a);b&&(f=ja(b.mid,p));(f=(f=f||p.star)&&ja(a,f[1]))&&(a=f[1]+a.substring(f[3]));b=(O=a.match(/^([^\/]+)(\/(.+))?$/))?O[1]:"";(q=c[b])?a=b+"/"+(n=O[3]||q.main):b="";var l=0;s(g,function(b){var c=a.match(b[0]);c&&0<c.length&&(l=A(b[1])?a.replace(b[0],b[1]):b[1])});if(l)return Ba(l,0,c,d,k,p,e,g,h);if(c=d[a])return h?W(c.pid,c.mid,c.pack,
c.url):d[a];d=(f=ja(a,e))?f[1]+a.substring(f[3]):b?q.location+"/"+n:a;/(^\/)|(\:)/.test(d)||(d=k+d);return W(b,a,q,Aa(d+".js"))},T=function(a,b,c){return Ba(a,b,ca,v,e.baseUrl,c?[]:R,c?[]:ta,c?[]:sa)},Ca=function(a,b,c){return a.normalize?a.normalize(b,function(a){return ia(a,c)}):ia(b,c)},Da=0,G=function(a,b,c){var d,k;(d=a.match(/^(.+?)\!(.*)$/))?(k=G(d[1],b,c),5===k.executed&&!k.load&&ka(k),k.load?(d=Ca(k,d[2],b),a=k.mid+"!"+(k.dynamic?++Da+"!":"")+d):(d=d[2],a=k.mid+"!"+ ++Da+"!waitingForPlugin"),
a={plugin:k,mid:a,req:ea(b),prid:d}):a=T(a,b);return v[a.mid]||!c&&(v[a.mid]=a)},ia=e.toAbsMid=function(a,b){return T(a,b).mid},va=e.toUrl=function(a,b){var c=T(a+"/x",b),d=c.url;return Ea(0===c.pid?a:d.substring(0,d.length-5))},Fa={injected:2,executed:5,def:3,result:3},E=function(a){return v[a]=f({mid:a},Fa)},Pa=E("require"),Qa=E("exports"),Ra=E("module"),$={},la=0,ka=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;return a},Sa=function(a){var b={};s(a.loadQ,
function(c){var d=Ca(a,c.prid,c.req.module),e=a.dynamic?c.mid.replace(/waitingForPlugin$/,d):a.mid+"!"+d,d=f(f({},c),{mid:e,prid:d,injected:0});v[e]||Ga(v[e]=d);b[c.mid]=v[e];Z(c);delete v[c.mid]});a.loadQ=0;var c=function(a){for(var c=a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},d;for(d in v)c(v[d]);s(C,c)},ma=function(a){e.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=la++;a.loadQ&&(ka(a),Sa(a));for(g=0;g<C.length;)C[g]===a?C.splice(g,1):g++;/^require\*/.test(a.mid)&&delete v[a.mid]},
Ta=[],ha=function(a,b){if(4===a.executed)return e.trace("loader-circular-dependency",[Ta.concat(a.mid).join("-\x3e")]),!a.def||b?$:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return $;var c=a.mid,d=a.deps||[],k,p=[],f=0;for(a.executed=4;k=d[f++];){k=k===Pa?ea(a):k===Qa?a.cjs.exports:k===Ra?a.cjs:ha(k,b);if(k===$)return a.executed=0,e.trace("loader-exec-module",["abort",c]),$;p.push(k)}e.trace("loader-run-factory",[a.mid]);c=a.def;p=A(c)?c.apply(null,p):c;a.result=void 0===p&&a.cjs?a.cjs.exports:
p;ma(a)}return a.result},P=0,ga=function(a){try{P++,a()}finally{P--}Oa()&&I("idle",[])},X=function(){P||ga(function(){for(var a,b,c=0;c<C.length;)a=la,b=C[c],ha(b),a!=la?c=0:c++})},Ea="function"==typeof h.fixupUrl?h.fixupUrl:function(a){a+="";return a+(da?(/\?/.test(a)?"\x26":"?")+da:"")},Ga=function(a){var b=a.plugin;5===b.executed&&!b.load&&ka(b);var c=function(b){a.result=b;Z(a);ma(a);X()};b.load?b.load(a.prid,a.req,c):b.loadQ?b.loadQ.push(a):(b.loadQ=[a],C.unshift(b),za(b))},aa=0,na=0,oa=0,Ua=
function(a,b){u("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));oa=1;a===aa?aa.call(null):e.eval(a,b.url);oa=0},za=function(a){var b=a.mid,c=a.url;if(!a.executed&&!a.injected&&!(z[b]||a.url&&(a.pack&&z[a.url]===a.pack||1==z[a.url])))if(Ma(a),a.plugin)Ga(a);else{var d=function(){Va(a);if(2!==a.injected){if(u("dojo-enforceDefine")){I("error",w("noDefine",a));return}Z(a);f(a,Fa);e.trace("loader-define-nonmodule",[a.url])}X()};(aa=J[b]||J["url:"+a.url])?(e.trace("loader-inject",["cache",a.mid,
c]),Ua(aa,a),d()):(e.trace("loader-inject",["script",a.mid,c]),na=a,e.injectUrl(Ea(c),d,a),na=0)}},pa=function(a,b,c){e.trace("loader-define-module",[a.mid,b]);if(2===a.injected)return I("error",w("multipleDefine",a)),a;f(a,{deps:b,def:c,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var d=0;b[d];d++)b[d]=G(b[d],a);Z(a);!A(c)&&!b.length&&(a.result=c,ma(a));return a},Va=function(a,b){for(var c=[],d,e;Y.length;)e=Y.shift(),
b&&(e[0]=b.shift()),d=e[0]&&G(e[0])||a,c.push([d,e[1],e[2]]);U(a);s(c,function(a){V(pa.apply(null,a))})},Na=l,La=l;u.add("ie-event-behavior",q.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var qa=function(a,b,c,d){if(u("ie-event-behavior"))return a.attachEvent(c,d),function(){a.detachEvent(c,d)};a.addEventListener(b,d,!1);return function(){a.removeEventListener(b,d,!1)}},Wa=qa(window,"load","onload",function(){e.pageLoaded=1;"complete"!=
q.readyState&&(q.readyState="complete");Wa()}),E=q.getElementsByTagName("script");for(g=0;!K;)if(!/^dojo/.test((x=E[g++])&&x.type))K=x;e.injectUrl=function(a,b,c){c=c.node=q.createElement("script");var d=qa(c,"load","onreadystatechange",function(a){a=a||window.event;var c=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(c.readyState))d(),e(),b&&b()}),e=qa(c,"error","onerror",function(b){d();e();I("error",w("scriptError",[a,b]))});c.type="text/javascript";c.charset="utf-8";c.src=a;
K.parentNode.insertBefore(c,K);return c};e.log=l;e.trace=l;x=function(a,b,c){var d=arguments.length,k=["require","exports","module"],f=[0,a,b];1==d?f=[0,A(a)?k:[],a]:2==d&&t(a)?f=[a,A(b)?k:[],b]:3==d&&(f=[a,b,c]);e.trace("loader-define",f.slice(0,2));if((d=f[0]&&G(f[0]))&&!z[d.mid])V(pa(d,f[1],f[2]));else if(!u("ie-event-behavior")||oa)Y.push(f);else{d=d||na;if(!d)for(a in z)if((k=v[a])&&k.node&&"interactive"===k.node.readyState){d=k;break}d?(U(d),V(pa(d,f[1],f[2]))):I("error",w("ieDefineFailed",
f[0]));X()}};x.amd={vendor:"dojotoolkit.org"};f(f(e,m.loaderPatch),h.loaderPatch);Q("error",function(a){try{if(a instanceof Error)for(var b in a);}catch(c){}});f(e,{uid:M,cache:J,packs:ca});D.define||(D.define=x,D.require=e,s(ya,function(a){N(a)}),Q=B.deps||h.deps||m.deps,B=B.callback||h.callback||m.callback,e.boot=Q||B?[Q||[],B]:0)})(this.dojoConfig||this.djConfig||this.require||{},{async:1,hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,
"host-browser":1},packages:[{location:".",name:"dojo"},{location:"../dijit",name:"dijit"},{location:"../core",name:"core"},{location:"../kitsonkelly-client",name:"kitsonkelly-client"}]});
require({cache:{"kitsonkelly-client/main":function(){define(["core/dom","core/on","dojo/domReady!"],function(h,m){var g=h.query(".photos \x3e a"),l=h.get("photo-viewer"),n=l?h.query("#photo-viewer img")[0]:void 0;h.query("#photo-viewer .close").on("click",function(g){g&&g.preventDefault();h.modify(l,".hidden")});l&&m(l,"click",function(g){g&&g.preventDefault();h.modify(l,".hidden")});if(g.length)g.on("click",function(g){g&&g.preventDefault();n.src=g.target.src.replace("/thumb/","/full/");h.modify(l,
"!.hidden")})})},"dojo/domReady":function(){define(["./has"],function(h){function m(e){r.push(e);t&&g()}function g(){if(!s){for(s=!0;r.length;)try{r.shift()(n)}catch(e){}s=!1;m._onQEmpty()}}var l=function(){return this}(),n=document,y={loaded:1,complete:1},A="string"!=typeof n.readyState,t=!!y[n.readyState],r=[],s;m.load=function(e,f,g){m(g)};m._Q=r;m._onQEmpty=function(){};A&&(n.readyState="loading");if(!t){var f=[],w=function(e){e=e||l.event;t||"readystatechange"==e.type&&!y[n.readyState]||(A&&
(n.readyState="complete"),t=1,g())},H=function(e,f){e.addEventListener(f,w,!1);r.push(function(){e.removeEventListener(f,w,!1)})};if(!h("dom-addeventlistener")){var H=function(e,f){f="on"+f;e.attachEvent(f,w);r.push(function(){e.detachEvent(f,w)})},M=n.createElement("div");try{M.doScroll&&null===l.frameElement&&f.push(function(){try{return M.doScroll("left"),1}catch(e){}})}catch(e){}}H(n,"DOMContentLoaded");H(l,"load");"onreadystatechange"in n?H(n,"readystatechange"):A||f.push(function(){return y[n.readyState]});
if(f.length){var D=function(){if(!t){for(var e=f.length;e--;)if(f[e]()){w("poller");return}setTimeout(D,30)}};D()}}return m})},"dojo/has":function(){define(["require","module"],function(h,m){var g=h.has||function(){};g.add("dom-addeventlistener",!!document.addEventListener);g.add("touch","ontouchstart"in document||"onpointerdown"in document&&0<navigator.maxTouchPoints||window.navigator.msMaxTouchPoints);g.add("touch-events","ontouchstart"in document);g.add("pointer-events","onpointerdown"in document);
g.add("MSPointer","msMaxTouchPoints"in navigator);g.add("device-width",screen.availWidth||innerWidth);var l=document.createElement("form");g.add("dom-attributes-explicit",0==l.attributes.length);g.add("dom-attributes-specified-flag",0<l.attributes.length&&40>l.attributes.length);g.clearElement=function(g){g.innerHTML="";return g};g.normalize=function(h,l){var m=h.match(/[\?:]|[^:\?]*/g),t=0,r=function(h){var f=m[t++];if(":"==f)return 0;if("?"==m[t++]){if(!h&&g(f))return r();r(!0);return r(h)}return f||
0};return(h=r())&&l(h)};g.load=function(g,h,l){g?h([g],l):l()};return g})}}});(function(){var h=this.require;h({cache:{}});!h.async&&h(["dojo"]);h.boot&&h.apply(null,h.boot)})();
//# sourceMappingURL=dojo.js.map