//>>built
require({cache:{"dojo/node":function(){define("dojo/node",["dojo/has"],function(){throw Error("node plugin failed to load because environment is not Node.js");})},"dojo/has":function(){define("dojo/has",["require","module"],function(d){var b=d.has||function(){};b.add("dom-addeventlistener",!!document.addEventListener);b.add("touch","ontouchstart"in document);b.add("device-width",screen.availWidth||innerWidth);d=document.createElement("form");b.add("dom-attributes-explicit",0==d.attributes.length);
b.add("dom-attributes-specified-flag",0<d.attributes.length&&40>d.attributes.length);b.clearElement=function(e){e.innerHTML="";return e};b.normalize=function(e,d){var k=e.match(/[\?:]|[^:\?]*/g),m=0,h=function(e){var c=k[m++];if(":"==c)return 0;if("?"==k[m++]){if(!e&&b(c))return h();h(!0);return h(e)}return c||0};return(e=h())&&d(e)};b.load=function(e,b,d){e?b([e],d):d()};return b})},"dojo/Deferred":function(){define("dojo/Deferred",["./has","./_base/lang","./errors/CancelError","./promise/Promise",
"./promise/instrumentation"],function(d,b,e,i,k){var m=Object.freeze||function(){},h=function(a,f,c,h,e){2===f&&g.instrumentRejected&&0===a.length&&g.instrumentRejected(c,!1,h,e);for(e=0;e<a.length;e++)j(a[e],f,c,h)},j=function(l,f,n,e){var h=l[f],b=l.deferred;if(h)try{var d=h(n);if(d&&"function"===typeof d.then){l.cancel=d.cancel;d.then(c(b,1),c(b,2),c(b,0));return}a(b,1,d)}catch(j){a(b,2,j)}else a(b,f,n);2===f&&g.instrumentRejected&&g.instrumentRejected(n,!!h,e,b.promise)},c=function(l,f){return function(g){a(l,
f,g)}},a=function(a,f,g){if(!a.isCanceled())switch(f){case 0:a.progress(g);break;case 1:a.resolve(g);break;case 2:a.reject(g)}},g=function(a){var f=this.promise=new i,c=this,b,d,k,s=!1,p=[];Error.captureStackTrace&&(Error.captureStackTrace(c,g),Error.captureStackTrace(f,g));this.isResolved=f.isResolved=function(){return 1===b};this.isRejected=f.isRejected=function(){return 2===b};this.isFulfilled=f.isFulfilled=function(){return!!b};this.isCanceled=f.isCanceled=function(){return s};this.progress=function(a,
g){if(b){if(!0===g)throw Error("This deferred has already been fulfilled.");return f}h(p,0,a,null,c);return f};this.resolve=function(a,g){if(b){if(!0===g)throw Error("This deferred has already been fulfilled.");return f}h(p,b=1,d=a,null,c);p=null;return f};var t=this.reject=function(a,g){if(b){if(!0===g)throw Error("This deferred has already been fulfilled.");return f}Error.captureStackTrace&&Error.captureStackTrace(k={},t);h(p,b=2,d=a,k,c);p=null;return f};this.then=f.then=function(a,c,l){var n=
[l,a,c];n.cancel=f.cancel;n.deferred=new g(function(a){return n.cancel&&n.cancel(a)});b&&!p?j(n,b,d,k):p.push(n);return n.deferred.promise};this.cancel=f.cancel=function(g,c){if(b){if(!0===c)throw Error("This deferred has already been fulfilled.");}else{if(a)var f=a(g),g="undefined"===typeof f?g:f;s=!0;if(b){if(2===b&&d===g)return g}else return"undefined"===typeof g&&(g=new e),t(g),g}};m(f)};g.prototype.toString=function(){return"[object Deferred]"};k&&k(g);return g})},"dojo/_base/lang":function(){define("dojo/_base/lang",
["./kernel","../has","../sniff"],function(d,b){b.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var e=b("bug-for-in-skips-shadowed")?"hasOwnProperty.valueOf.isPrototypeOf.propertyIsEnumerable.toLocaleString.toString.constructor".split("."):[],i=e.length,k=function(a,g,c){var f,n=0,b=d.global;if(!c)if(a.length){f=a[n++];try{c=d.scopeMap[f]&&d.scopeMap[f][1]}catch(h){}c=c||(f in b?b[f]:g?b[f]={}:void 0)}else return b;for(;c&&(f=a[n++]);)c=f in c?c[f]:g?c[f]=
{}:void 0;return c},m=Object.prototype.toString,h=function(a,g,c){return(c||[]).concat(Array.prototype.slice.call(a,g||0))},j=/\{([^\}]+)\}/g,c={_extraNames:e,_mixin:function(a,g,c){var f,n,h,d={};for(f in g)if(n=g[f],!(f in a)||a[f]!==n&&(!(f in d)||d[f]!==n))a[f]=c?c(n):n;if(b("bug-for-in-skips-shadowed")&&g)for(h=0;h<i;++h)if(f=e[h],n=g[f],!(f in a)||a[f]!==n&&(!(f in d)||d[f]!==n))a[f]=c?c(n):n;return a},mixin:function(a,g){a||(a={});for(var l=1,f=arguments.length;l<f;l++)c._mixin(a,arguments[l]);
return a},setObject:function(a,c,l){var f=a.split("."),a=f.pop();return(l=k(f,!0,l))&&a?l[a]=c:void 0},getObject:function(a,c,l){return k(a.split("."),c,l)},exists:function(a,g){return void 0!==c.getObject(a,!1,g)},isString:function(a){return"string"==typeof a||a instanceof String},isArray:function(a){return a&&(a instanceof Array||"array"==typeof a)},isFunction:function(a){return"[object Function]"===m.call(a)},isObject:function(a){return void 0!==a&&(null===a||"object"==typeof a||c.isArray(a)||
c.isFunction(a))},isArrayLike:function(a){return a&&void 0!==a&&!c.isString(a)&&!c.isFunction(a)&&!(a.tagName&&"form"==a.tagName.toLowerCase())&&(c.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!c.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(""+a)},extend:function(a,g){for(var l=1,f=arguments.length;l<f;l++)c._mixin(a.prototype,arguments[l]);return a},_hitchArgs:function(a,g){var l=c._toArray(arguments,2),f=c.isString(g);return function(){var n=c._toArray(arguments),b=f?(a||d.global)[g]:
g;return b&&b.apply(a||this,l.concat(n))}},hitch:function(a,g){if(2<arguments.length)return c._hitchArgs.apply(d,arguments);g||(g=a,a=null);if(c.isString(g)){a=a||d.global;if(!a[g])throw['lang.hitch: scope["',g,'"] is null (scope="',a,'")'].join("");return function(){return a[g].apply(a,arguments||[])}}return!a?g:function(){return g.apply(a,arguments||[])}},delegate:function(){function a(){}return function(g,l){a.prototype=g;var f=new a;a.prototype=null;l&&c._mixin(f,l);return f}}(),_toArray:b("ie")?
function(){function a(a,c,f){f=f||[];for(c=c||0;c<a.length;c++)f.push(a[c]);return f}return function(c){return(c.item?a:h).apply(this,arguments)}}():h,partial:function(a){return c.hitch.apply(d,[null].concat(c._toArray(arguments)))},clone:function(a){if(!a||"object"!=typeof a||c.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var g,l,f;if(c.isArray(a)){g=[];for(l=0,f=a.length;l<f;++l)l in
a&&g.push(c.clone(a[l]))}else g=a.constructor?new a.constructor:{};return c._mixin(g,a,c.clone)},trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,g,l){return a.replace(l||j,c.isFunction(g)?g:function(a,l){return c.getObject(l,!1,g)})}};c.mixin(d,c);return c})},"dojo/_base/kernel":function(){define("dojo/_base/kernel",["../has","./config","require","module"],function(d,b,e,i){var k,m={},h={},j={config:b,global:this,
dijit:m,dojox:h},m={dojo:["dojo",j],dijit:["dijit",m],dojox:["dojox",h]},i=e.map&&e.map[i.id.match(/[^\/]+/)[0]];for(k in i)m[k]?m[k][0]=i[k]:m[k]=[i[k],{}];for(k in m)i=m[k],i[1]._scopeName=i[0],b.noGlobals||(this[i[0]]=i[1]);j.scopeMap=m;j.baseUrl=j.config.baseUrl=e.baseUrl;j.isAsync=e.async;j.locale=b.locale;i="$Rev$".match(/\d+/);j.version={major:1,minor:8,patch:0,flag:"dev",revision:i?+i[0]:NaN,toString:function(){var a=j.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+
")"}};Function("d","d.eval = function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(j);j.exit=function(){};"undefined"!=typeof console||(console={});for(var m="assert,count,debug,dir,dirxml,error,group,groupEnd,info,profile,profileEnd,time,timeEnd,trace,warn,log".split(","),c,i=0;c=m[i++];)console[c]||function(){var a=c+"";console[a]="log"in console?function(){var c=Array.apply({},arguments);c.unshift(a+":");console.log(c.join(" "))}:function(){};console[a]._fake=!0}();
d.add("dojo-debug-messages",!!b.isDebug);j.deprecated=j.experimental=function(){};if(d("dojo-debug-messages"))j.deprecated=function(a,c,l){a="DEPRECATED: "+a;c&&(a+=" "+c);l&&(a+=" -- will be removed in version: "+l);console.warn(a)},j.experimental=function(a,c){var l="EXPERIMENTAL: "+a+" -- APIs subject to change without notice.";c&&(l+=" "+c);console.warn(l)};if(b.modulePaths){j.deprecated("dojo.modulePaths","use paths configuration");d={};for(k in b.modulePaths)d[k.replace(/\./g,"/")]=b.modulePaths[k];
e({paths:d})}j.moduleUrl=function(a,c){j.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var l=null;a&&(l=e.toUrl(a.replace(/\./g,"/")+(c?"/"+c:"")+"/*.*").replace(/\/\*\.\*/,"")+(c?"":"/"));return l};j._hasResource={};return j})},"dojo/_base/config":function(){define("dojo/_base/config",["../has","require"],function(d,b){var e={},i=b.rawConfig,k;for(k in i)e[k]=i[k];return e})},"dojo/sniff":function(){define("dojo/sniff",["./has"],function(d){var b=navigator,e=b.userAgent,b=b.appVersion,
i=parseFloat(b);d.add("air",0<=e.indexOf("AdobeAIR"));d.add("khtml",0<=b.indexOf("Konqueror")?i:void 0);d.add("webkit",parseFloat(e.split("WebKit/")[1])||void 0);d.add("chrome",parseFloat(e.split("Chrome/")[1])||void 0);d.add("safari",0<=b.indexOf("Safari")&&!d("chrome")?parseFloat(b.split("Version/")[1]):void 0);d.add("mac",0<=b.indexOf("Macintosh"));d.add("quirks","BackCompat"==document.compatMode);d.add("ios",/iPhone|iPod|iPad/.test(e));d.add("android",parseFloat(e.split("Android ")[1])||void 0);
if(!d("webkit")){0<=e.indexOf("Opera")&&d.add("opera",9.8<=i?parseFloat(e.split("Version/")[1])||i:i);0<=e.indexOf("Gecko")&&!d("khtml")&&!d("webkit")&&d.add("mozilla",i);d("mozilla")&&d.add("ff",parseFloat(e.split("Firefox/")[1]||e.split("Minefield/")[1])||void 0);if(document.all&&!d("opera"))e=parseFloat(b.split("MSIE ")[1])||void 0,(b=document.documentMode)&&5!=b&&Math.floor(e)!=b&&(e=b),d.add("ie",e);d.add("wii","undefined"!=typeof opera&&opera.wiiremote)}return d})},"dojo/errors/CancelError":function(){define("dojo/errors/CancelError",
["./create"],function(d){return d("CancelError",null,null,{dojoType:"cancel"})})},"dojo/errors/create":function(){define("dojo/errors/create",["../_base/lang"],function(d){return function(b,e,i,k){var i=i||Error,m=function(b){if(i===Error){Error.captureStackTrace&&Error.captureStackTrace(this,m);var d=Error.call(this,b),c;for(c in d)d.hasOwnProperty(c)&&(this[c]=d[c]);this.message=b}else i.apply(this,arguments);e&&e.apply(this,arguments)};m.prototype=d.delegate(i.prototype,k);m.prototype.name=b;return m.prototype.constructor=
m}})},"dojo/promise/Promise":function(){define("dojo/promise/Promise",["../_base/lang"],function(d){function b(){throw new TypeError("abstract");}return d.extend(function(){},{then:function(){b()},cancel:function(){b()},isResolved:function(){b()},isRejected:function(){b()},isFulfilled:function(){b()},isCanceled:function(){b()},always:function(b){return this.then(b,b)},otherwise:function(b){return this.then(null,b)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},
"dojo/promise/instrumentation":function(){define("dojo/promise/instrumentation",["./tracer","../has","../_base/lang","../_base/array"],function(d,b,e,i){function k(a,c,g){var b="";a&&a.stack&&(b+=a.stack);c&&c.stack&&(b+="\n    ----------------------------------------\n    rejected"+c.stack.split("\n").slice(1).join("\n").replace(/^\s+/," "));g&&g.stack&&(b+="\n    ----------------------------------------\n"+g.stack);console.error(a,b)}function m(a,c,g,b){c||k(a,g,b)}function h(b,f,h,d){f?i.some(c,
function(a,g){if(a.error===b)return c.splice(g,1),!0}):i.some(c,function(a){return a.error===b})||c.push({error:b,rejection:h,deferred:d,timestamp:(new Date).getTime()});a||(a=setTimeout(j,g))}function j(){var b=(new Date).getTime(),f=b-g;c=i.filter(c,function(a){return a.timestamp<f?(k(a.error,a.rejection,a.deferred),!1):!0});c.length&&(a=setTimeout(j,c[0].timestamp+g-b))}var c=[],a=!1,g=1E3;return function(a){var c=b("config-useDeferredInstrumentation");if(c){d.on("resolved",e.hitch(console,"log",
"resolved"));d.on("rejected",e.hitch(console,"log","rejected"));d.on("progress",e.hitch(console,"log","progress"));var n=[];"string"===typeof c&&(n=c.split(","),c=n.shift());if("report-rejections"===c)a.instrumentRejected=m;else if("report-unhandled-rejections"===c||!0===c||1===c)a.instrumentRejected=h,g=parseInt(n[0],10)||g;else throw Error("Unsupported instrumentation usage <"+c+">");}}})},"dojo/promise/tracer":function(){define("dojo/promise/tracer",["../_base/lang","./Promise","../Evented"],function(d,
b,e){function i(b){setTimeout(function(){m.apply(k,b)},0)}var k=new e,m=k.emit;k.emit=null;b.prototype.trace=function(){var b=d._toArray(arguments);this.then(function(d){i(["resolved",d].concat(b))},function(d){i(["rejected",d].concat(b))},function(d){i(["progress",d].concat(b))});return this};b.prototype.traceRejected=function(){var b=d._toArray(arguments);this.otherwise(function(d){i(["rejected",d].concat(b))});return this};return k})},"dojo/Evented":function(){define("dojo/Evented",["./aspect",
"./on"],function(d,b){function e(){}var i=d.after;e.prototype={on:function(d,e){return b.parse(this,d,e,function(b,d){return i(b,"on"+d,e,!0)})},emit:function(d,e){var h=[this];h.push.apply(h,arguments);return b.emit.apply(b,h)}};return e})},"dojo/aspect":function(){define("dojo/aspect",[],function(){function d(b,c,a,g){var d=b[c],f="around"==c,e;if(f){var h=a(function(){return d.advice(this,arguments)});e={remove:function(){e.cancelled=!0},advice:function(a,c){return e.cancelled?d.advice(a,c):h.apply(a,
c)}}}else e={remove:function(){var a=e.previous,g=e.next;if(!g&&!a)delete b[c];else if(a?a.next=g:b[c]=g,g)g.previous=a},id:i++,advice:a,receiveArguments:g};if(d&&!f)if("after"==c){for(a=d;a;)d=a,a=a.next;d.next=e;e.previous=d}else{if("before"==c)b[c]=e,e.next=d,d.previous=e}else b[c]=e;return e}function b(b){return function(c,a,g,h){var f=c[a],n;if(!f||f.target!=c){c[a]=n=function(){for(var a=i,c=arguments,b=n.before;b;)c=b.advice.apply(this,c)||c,b=b.next;if(n.around)var g=n.around.advice(this,
c);for(b=n.after;b&&b.id<a;){if(b.receiveArguments)var f=b.advice.apply(this,c),g=f===e?g:f;else g=b.advice.call(this,g,c);b=b.next}return g};if(f)n.around={advice:function(a,c){return f.apply(a,c)}};n.target=c}c=d(n||f,b,g,h);g=null;return c}}var e,i=0,k=b("after"),m=b("before"),h=b("around");return{before:m,around:h,after:k}})},"dojo/on":function(){define("dojo/on",["./has!dom-addeventlistener?:./aspect","./_base/kernel","./has"],function(d,b,e){function i(a,b,g,f,d){if(f=b.match(/(.*):(.*)/))return b=
f[2],f=f[1],j.selector(f,b).call(d,a,g);e("touch")&&(c.test(b)&&(g=w(g)),!e("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,g=w(g)));n&&(g=n(g));if(a.addEventListener){var h=b in l,i=h?l[b]:b;a.addEventListener(i,g,h);return{remove:function(){a.removeEventListener(i,g,h)}}}if(s&&a.attachEvent)return s(a,"on"+b,g);throw Error("Target must be an event emitter");}function k(){this.cancelable=!1}function m(){this.bubbles=!1}var h=window.ScriptEngineMajorVersion;e.add("jscript",
h&&h()+ScriptEngineMinorVersion()/10);e.add("event-orientationchange",e("touch")&&!e("android"));e.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);var j=function(a,c,b,g){return a.on&&"function"!=typeof c?a.on(c,b):j.parse(a,c,b,i,g,this)};j.pausable=function(a,c,b,g){var f,a=j(a,c,function(){if(!f)return b.apply(this,arguments)},g);a.pause=function(){f=!0};a.resume=function(){f=!1};return a};j.once=function(a,c,b){var g=
j(a,c,function(){g.remove();return b.apply(this,arguments)});return g};j.parse=function(a,c,b,g,f,d){if(c.call)return c.call(d,a,b);if(-1<c.indexOf(",")){for(var c=c.split(/\s*,\s*/),e=[],h=0,l;l=c[h++];)e.push(g(a,l,b,f,d));e.remove=function(){for(var a=0;a<e.length;a++)e[a].remove()};return e}return g(a,c,b,f,d)};var c=/^touch/;j.selector=function(a,c,g){return function(f,d){function e(c){for(h=h&&h.matches?h:b.query;!h.matches(c,a,f);)if(c==f||!1===g||!(c=c.parentNode)||1!=c.nodeType)return;return c}
var h="function"==typeof a?{matches:a}:this,l=c.bubble;return l?j(f,l(e),d):j(f,c,function(a){var c=e(a.target);return c&&d.call(c,a)})}};var a=[].slice,g=j.emit=function(c,b,g){var f=a.call(arguments,2),d="on"+b;if("parentNode"in c){var e=f[0]={},h;for(h in g)e[h]=g[h];e.preventDefault=k;e.stopPropagation=m;e.target=c;e.type=b;g=e}do c[d]&&c[d].apply(c,f);while(g&&g.bubbles&&(c=c.parentNode));return g&&g.cancelable&&g},l={};if(!e("event-stopimmediatepropagation"))var f=function(){this.modified=this.immediatelyStopped=
!0},n=function(a){return function(c){if(!c.immediatelyStopped)return c.stopImmediatePropagation=f,a.apply(this,arguments)}};if(e("dom-addeventlistener")){l={focusin:"focus",focusout:"blur"};if(e("opera"))l.keydown="keypress";j.emit=function(a,c,b){if(a.dispatchEvent&&document.createEvent){var f=a.ownerDocument.createEvent("HTMLEvents");f.initEvent(c,!!b.bubbles,!!b.cancelable);for(var d in b)d in f||(f[d]=b[d]);return a.dispatchEvent(f)&&f}return g.apply(j,arguments)}}else{j._fixEvent=function(a,
c){if(!a)a=(c&&(c.ownerDocument||c.document||c).parentWindow||window).event;if(!a)return a;o&&a.type==o.type&&(a=o);if(!a.target){a.target=a.srcElement;a.currentTarget=c||a.srcElement;if("mouseover"==a.type)a.relatedTarget=a.fromElement;if("mouseout"==a.type)a.relatedTarget=a.toElement;if(!a.stopPropagation)a.stopPropagation=p,a.preventDefault=t;switch(a.type){case "keypress":var b="charCode"in a?a.charCode:a.keyCode;10==b?(b=0,a.keyCode=13):13==b||27==b?b=0:3==b&&(b=99);a.charCode=b;b=a;b.keyChar=
b.charCode?String.fromCharCode(b.charCode):"";b.charOrCode=b.keyChar||b.keyCode}}return a};var o,q=function(a){this.handle=a};q.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var r=function(a){return function(c){var c=j._fixEvent(c,this),b=a.call(this,c);c.modified&&(o||setTimeout(function(){o=null}),o=c);return b}},s=function(a,c,b){b=r(b);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>e("jscript"))&&!e("config-_allow_leaks")){"undefined"==
typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var g=a[c];if(!g||!g.listeners){var f=g,g=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");g.listeners=[];a[c]=g;g.global=this;f&&g.listeners.push(_dojoIEListeners_.push(f)-1)}g.listeners.push(a=g.global._dojoIEListeners_.push(b)-1);return new q(a)}return d.after(a,c,b,!0)},p=function(){this.cancelBubble=
!0},t=j._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1}}if(e("touch"))var u=function(){},v=window.orientation,w=function(a){return function(c){var b=c.corrected;if(!b){var g=c.type;try{delete c.type}catch(f){}c.type?(u.prototype=c,b=new u,b.preventDefault=function(){c.preventDefault()},b.stopPropagation=function(){c.stopPropagation()}):(b=c,b.type=g);c.corrected=b;if("resize"==g){if(v==window.orientation)return null;
v=window.orientation;b.type="orientationchange";return a.call(this,b)}if(!("rotation"in b))b.rotation=0,b.scale=1;var g=b.changedTouches[0],d;for(d in g)delete b[d],b[d]=g[d]}return a.call(this,b)}};return j})},"dojo/_base/array":function(){define("dojo/_base/array",["./kernel","../has","./lang"],function(d,b,e){function i(a){return h[a]=new Function("item","index","array",a)}function k(a){var c=!a;return function(b,f,d){var e=0,k=b&&b.length||0,j;k&&"string"==typeof b&&(b=b.split(""));"string"==
typeof f&&(f=h[f]||i(f));if(d)for(;e<k;++e){if(j=!f.call(d,b[e],e,b),a^j)return!j}else for(;e<k;++e)if(j=!f(b[e],e,b),a^j)return!j;return c}}function m(a){var b=1,d=0,f=0;a||(b=d=f=-1);return function(e,h,i,k){if(k&&0<b)return c.lastIndexOf(e,h,i);var k=e&&e.length||0,m=a?k+f:d;i===j?i=a?d:k+f:0>i?(i=k+i,0>i&&(i=d)):i=i>=k?k+f:i;for(k&&"string"==typeof e&&(e=e.split(""));i!=m;i+=b)if(e[i]==h)return i;return-1}}var h={},j,c={every:k(!1),some:k(!0),indexOf:m(!0),lastIndexOf:m(!1),forEach:function(a,
c,b){var f=0,d=a&&a.length||0;d&&"string"==typeof a&&(a=a.split(""));"string"==typeof c&&(c=h[c]||i(c));if(b)for(;f<d;++f)c.call(b,a[f],f,a);else for(;f<d;++f)c(a[f],f,a)},map:function(a,c,b,f){var d=0,e=a&&a.length||0,f=new (f||Array)(e);e&&"string"==typeof a&&(a=a.split(""));"string"==typeof c&&(c=h[c]||i(c));if(b)for(;d<e;++d)f[d]=c.call(b,a[d],d,a);else for(;d<e;++d)f[d]=c(a[d],d,a);return f},filter:function(a,c,b){var d=0,e=a&&a.length||0,k=[],j;e&&"string"==typeof a&&(a=a.split(""));"string"==
typeof c&&(c=h[c]||i(c));if(b)for(;d<e;++d)j=a[d],c.call(b,j,d,a)&&k.push(j);else for(;d<e;++d)j=a[d],c(j,d,a)&&k.push(j);return k},clearCache:function(){h={}}};e.mixin(d,c);return c})},"dojo/promise/all":function(){define("dojo/promise/all",["../_base/array","../Deferred","../when"],function(d,b,e){var i=d.some;return function(d){var m,h;d instanceof Array?h=d:d&&"object"===typeof d&&(m=d);var j,c=[];if(m){h=[];for(var a in m)Object.hasOwnProperty.call(m,a)&&(c.push(a),h.push(m[a]));j={}}else h&&
(j=[]);if(!h||!h.length)return(new b).resolve(j);var g=new b;g.promise.always(function(){j=c=null});var l=h.length;i(h,function(a,b){m||c.push(b);e(a,function(a){g.isFulfilled()||(j[c[b]]=a,0===--l&&g.resolve(j))},g.reject);return g.isFulfilled()});return g.promise}})},"dojo/when":function(){define("dojo/when",["./Deferred","./promise/Promise"],function(d,b){return function(e,i,k,m){var h=e&&"function"===typeof e.then,j=h&&e instanceof b;if(h){if(!j)h=new d(e.cancel),e.then(h.resolve,h.reject,h.progress),
e=h.promise}else return i?i(e):(new d).resolve(e);return i||k||m?e.then(i,k,m):e}})},"kitsonkelly/server/as":function(){define("kitsonkelly/server/as",["dojo/Deferred","dojo/request","dojo/request/handlers","dojo/node!xml2js"],function(d,b,e,i){e.register("xml2js",function(b){var e=new i.Parser,h=new d;e.parseString(b.text,function(b,c){b&&h.reject(b);h.resolve(c)});return h});return function(){return b.get("http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=kitsonk&api_key=b25b959554ed76058ac220b7b2e0a026",
{handleAs:"xml2js"}).then(function(b){return b})}})},"dojo/request":function(){define("dojo/request",["./request/default!"],function(d){return d})},"dojo/request/default":function(){define("dojo/request/default",["exports","require","../has"],function(d,b,e){var i=e("config-requestProvider");i||(i="./xhr");d.getPlatformDefaultId=function(){return"./xhr"};d.load=function(d,e,h){b(["platform"==d?"./xhr":i],function(b){h(b)})}})},"dojo/request/handlers":function(){define("dojo/request/handlers",["../json",
"../_base/kernel","../_base/array","../has"],function(d,b,e,i){function k(c){var a=j[c.options.handleAs];c.data=a?a(c):c.data||c.text;return c}i.add("activex","undefined"!==typeof ActiveXObject);var m;if(i("activex")){var h=["Msxml2.DOMDocument.6.0","Msxml2.DOMDocument.4.0","MSXML2.DOMDocument.3.0","MSXML.DOMDocument"];m=function(c){var a=c.data;if(!a||!a.documentElement){var b=c.text;e.some(h,function(c){try{var d=new ActiveXObject(c);d.async=!1;d.loadXML(b);a=d}catch(e){return!1}return!0})}return a}}var j=
{javascript:function(c){return b.eval(c.text||"")},json:function(c){return d.parse(c.text||null)},xml:m};k.register=function(c,a){j[c]=a};return k})},"dojo/json":function(){define("dojo/json",["./has"],function(d){var b="undefined"!=typeof JSON;d.add("json-parse",b);d.add("json-stringify",b&&'{"a":1}'==JSON.stringify({a:0},function(b,d){return d||1}));if(d("json-stringify"))return JSON;var e=function(b){return('"'+b.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,
"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};return{parse:d("json-parse")?JSON.parse:function(b,d){if(d&&!/^([\s\[\{]*(?:"(?:\\.|[^"])+"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(b))throw new SyntaxError("Invalid characters in JSON");return eval("("+b+")")},stringify:function(b,d,m){function h(c,a,b){d&&(c=d(b,c));var i;i=typeof c;if("number"==i)return isFinite(c)?c+"":"null";if("boolean"==i)return c+"";if(null===c)return"null";if("string"==typeof c)return e(c);
if("function"==i||"undefined"==i)return j;if("function"==typeof c.toJSON)return h(c.toJSON(b),a,b);if(c instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(a,b,d){a=c["getUTC"+b]()+(d?1:0);return 10>a?"0"+a:a});if(c.valueOf()!==c)return h(c.valueOf(),a,b);var f=m?a+m:"",n=m?" ":"",o=m?"\n":"";if(c instanceof Array){for(var n=c.length,q=[],b=0;b<n;b++)i=h(c[b],f,b),"string"!=typeof i&&(i="null"),q.push(o+f+i);return"["+q.join(",")+o+
a+"]"}q=[];for(b in c){var r;if(c.hasOwnProperty(b)){if("number"==typeof b)r='"'+b+'"';else if("string"==typeof b)r=e(b);else continue;i=h(c[b],f,b);"string"==typeof i&&q.push(o+f+r+":"+n+i)}}return"{"+q.join(",")+o+a+"}"}var j;"string"==typeof d&&(m=d,d=null);return h(b,"","")}}})}}});
require("dojo/node!util,dojo/node!express,dojo/node!jade,dojo/Deferred,dojo/promise/all,kitsonkelly/server/as".split(","),function(d,b,e,i,k,m){var h=b.createServer(),j=process.env.PORT||8001;h.configure(function(){h.set("view options",{layout:!1});h.set("view engine","jade");h.use(b.favicon("./images/favicon.ico"));h.use(b.cookieParser());h.use(b.session({secret:"yHCoyEPZ9WsNDORGb9SDDMNn0OOMcCgQiW5q8VFhDHJiztvvVVCPkZQWUAXl"}));h.use(h.router);h.use("/lib/dojo",b["static"]("../dojo"));h.use("/lib/dijit",
b["static"]("../dijit"));h.use("/lib/dojox",b["static"]("../dojox"));h.use("/lib",b["static"]("./lib"));h.use("/css",b["static"]("./css"));h.use("/images",b["static"]("./images"));h.use("/static",b["static"]("./static"));h.use(function(c,a){c.accepts("html")?(a.status(404),a.render("404",{url:c.url})):c.accepts("json")?a.send({error:"Not Found"}):a.type("txt").send("Not Found")});h.use(function(c,a,b){b.status(c.status||500);b.render("500",{error:c})})});h.get("/",function(c,a){a.render("index")});
h.get("/cv",function(c,a){a.render("cv")});h.get("/dojo",function(c,a){a.render("dojo")});h.get("/content/:view",function(c,a){a.render("content/"+c.params.view)});h.get("/page/:page",function(c,a,b){var d=new i;e.renderFile("views/content/"+c.params.page+".jade",{},function(a,c){a?d.reject(a):d.resolve(c)});if("cv"==c.params.page){var f=new i;e.renderFile("views/content/cv_nav.jade",{},function(a,c){a?f.reject(a):f.resolve(c)});d=k([d,f])}d.then(function(b){var d={title:"Kitson P. Kelly"};b instanceof
Array?(d.content=b[0],d.nav=b[1]):d.content=b;switch(c.params.page){case "home":d.connectItems=!0;d.subtitle="presence on the interwebs";break;case "dojo":d.connectItems=!1;d.subtitle="dojo toolkit";break;case "cv":d.connectItems=!1,d.subtitle="curriculum vitae/r\u00e9sum\u00e9"}a.json(d)},function(a){b(a)})});h.get("/views/:view",function(c,a){a.render(c.params.view)});h.get("/lastfm",function(c,a,b){m().then(function(b){a.json(b)},function(a){b(a)})});h.get("/404",function(b,a,d){d()});h.get("/403",
function(b,a,d){b=Error("not allowed!");b.status=403;d(b)});h.get("/500",function(b,a,d){d(Error("All your base are belong to us!"))});h.listen(j);d.puts("HTTP server started on port "+j)});